version: "3.7"
services:
  # redis8.1:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  #   container_name: redis8.1
  #   networks:
  #     - php8.1

  jws-api:
    build:
      args:
        user: zaynd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php8.1
    container_name: jws-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./ess-api:/var/www
    networks:
      - php8.1

  nginx-api:
    image: nginx:alpine
    container_name: nginx-api
    restart: unless-stopped
    ports:
      - 8180:80
    volumes:
      - ./ess-api:/var/www
      - ./config/nginx-api:/etc/nginx/conf.d/
    networks:
      - php8.1

  jws-fe:
    build:
      args:
        user: zaynd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php8.1
    container_name: jws-fe
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./ess-web:/var/www
    networks:
      - php8.1

  nginx-fe:
    image: nginx:alpine
    container_name: nginx-fe
    restart: unless-stopped
    ports:
      - 8181:80
    volumes:
      - ./ess-web:/var/www
      - ./config/nginx-fe:/etc/nginx/conf.d/
    networks:
      - php8.1
  
  app2u:
    build:
      args:
        user: zaynd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php8.1
    container_name: app2u
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app2u:/var/www
    networks:
      - php8.1

  nginx-app2u:
    image: nginx:alpine
    container_name: nginx-app2u
    restart: unless-stopped
    ports:
      - 8182:80
    volumes:
      - ./app2u:/var/www
      - ./config/nginx-app2u:/etc/nginx/conf.d/
    networks:
      - php8.1

  be-ecomm:
    build:
      args:
        user: zaynd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php8.1
    container_name: be-ecomm
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./be-ecommerce:/var/www
    networks:
      - php8.1

  nginx-ecom:
    image: nginx:alpine
    container_name: nginx-ecom
    restart: unless-stopped
    ports:
      - 8183:80
    volumes:
      - ./be-ecommerce:/var/www
      - ./config/nginx-ecom:/etc/nginx/conf.d/
    networks:
      - php8.1

  cpit-compro:
    build:
      args:
        user: zaynd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php8.1
    container_name: cpit-compro
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./cpit:/var/www
    networks:
      - php8.1

  nginx-compro:
    image: nginx:alpine
    container_name: nginx-compro
    restart: unless-stopped
    ports:
      - 8184:80
    volumes:
      - ./cpit:/var/www
      - ./config/nginx-compro:/etc/nginx/conf.d/
    networks:
      - php8.1
      
  be-donasi:
    build:
      args:
        user: zaynd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php8.1
    container_name: be-donasi
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./be-donasi:/var/www
    networks:
      - php8.1

  nginx-donasi:
    image: nginx:alpine
    container_name: nginx-donasi
    restart: unless-stopped
    ports:
      - 8185:80
    volumes:
      - ./be-donasi:/var/www
      - ./config/nginx-donasi:/etc/nginx/conf.d/
    networks:
      - php8.1

  travelaja:
    build:
      args:
        user: zaynd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php8.1
    container_name: travelaja
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./travelaja:/var/www
    networks:
      - php8.1

  nginx-travelaja:
    image: nginx:alpine
    container_name: nginx-travelaja
    restart: unless-stopped
    ports:
      - 8186:80
    volumes:
      - ./travelaja:/var/www
      - ./config/nginx-travelaja:/etc/nginx/conf.d/
    networks:
      - php8.1

  safety:
    build:
      args:
        user: zaynd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php8.1
    container_name: safety
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./safety-inspector:/var/www
    networks:
      - php8.1

  nginx-safety:
    image: nginx:alpine
    container_name: nginx-safety
    restart: unless-stopped
    ports:
      - 8187:80
    volumes:
      - ./safety-inspector:/var/www
      - ./config/nginx-safety:/etc/nginx/conf.d/
    networks:
      - php8.1

  husna:
    build:
      args:
        user: zaynd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php8.1
    container_name: husna
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./madal-husna:/var/www
    networks:
      - php8.1

  nginx-husna:
    image: nginx:alpine
    container_name: nginx-husna
    restart: unless-stopped
    ports:
      - 8188:80
    volumes:
      - ./madal-husna:/var/www
      - ./config/nginx-husna:/etc/nginx/conf.d/
    networks:
      - php8.1

  eis:
    build:
      args:
        user: zaynd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php8.1
    container_name: eis
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./eis-orange-integrate:/var/www
    networks:
      - php8.1

  nginx-eis:
    image: nginx:alpine
    container_name: nginx-eis
    restart: unless-stopped
    ports:
      - 8189:80
    volumes:
      - ./eis-orange-integrate:/var/www
      - ./config/nginx-eis:/etc/nginx/conf.d/
    networks:
      - php8.1

networks:
  php8.1:
    driver: bridge