version: "3.7"
services:
  # redis8.1:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  #   container_name: redis8.1
  #   networks:
  #     - php8.1

  jws-api:
    build:
      args:
        user: zaynd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php8.1
    container_name: jws-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./ess-api:/var/www
    networks:
      - php8.1

  nginx-api:
    image: nginx:alpine
    container_name: nginx-api
    restart: unless-stopped
    ports:
      - 8180:80
    volumes:
      - ./ess-api:/var/www
      - ./config/nginx-api:/etc/nginx/conf.d/
    networks:
      - php8.1

  jws-fe:
    build:
      args:
        user: zaynd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php8.1
    container_name: jws-fe
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./ess-web:/var/www
    networks:
      - php8.1

  nginx-fe:
    image: nginx:alpine
    container_name: nginx-fe
    restart: unless-stopped
    ports:
      - 8181:80
    volumes:
      - ./ess-web:/var/www
      - ./config/nginx-fe:/etc/nginx/conf.d/
    networks:
      - php8.1

  lara-product:
    build:
      args:
        user: zaynd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php8.1
    container_name: lara-product
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./lara-product:/var/www
    networks:
      - php8.1

  nginx-test:
    image: nginx:alpine
    container_name: nginx-test
    restart: unless-stopped
    ports:
      - 8182:80
    volumes:
      - ./lara-product:/var/www
      - ./config/nginx-test:/etc/nginx/conf.d/
    networks:
      - php8.1

  be-ecomm:
    build:
      args:
        user: zaynd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php8.1
    container_name: be-ecomm
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./be-ecommerce:/var/www
    networks:
      - php8.1

  nginx-ecom:
    image: nginx:alpine
    container_name: nginx-ecom
    restart: unless-stopped
    ports:
      - 8183:80
    volumes:
      - ./be-ecommerce:/var/www
      - ./config/nginx-ecom:/etc/nginx/conf.d/
    networks:
      - php8.1

  cpit-compro:
    build:
      args:
        user: zaynd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php8.1
    container_name: cpit-compro
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./cpit:/var/www
    networks:
      - php8.1

  nginx-compro:
    image: nginx:alpine
    container_name: nginx-compro
    restart: unless-stopped
    ports:
      - 8184:80
    volumes:
      - ./cpit:/var/www
      - ./config/nginx-compro:/etc/nginx/conf.d/
    networks:
      - php8.1

  test-loop:
    build:
      args:
        user: zaynd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php8.1
    container_name: test-loop
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./cpit:/var/www
    networks:
      - php8.1

  nginx-loop:
    image: nginx:alpine
    container_name: nginx-loop
    restart: unless-stopped
    ports:
      - 8185:80
    volumes:
      - ./test-loop:/var/www
      - ./config/nginx-loop:/etc/nginx/conf.d/
    networks:
      - php8.1

networks:
  php8.1:
    driver: bridge